---
title: "Airbnb"
output: html_document
date: "2024-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
easypackages::packages ("sf", "sp", "spdep", "spatialreg", "GWmodel", "tmap", "mapview", "car", "RColorBrewer", 
                        "cowplot", "leafsync", "leaflet.extras2", "mapview", "tidyverse", "patchwork", "GWRsel")
```

```{r}
project_directory <- dirname(getwd())
```

# Data

## Barcelona

```{r}
barcelona_map <- st_read(file.path(project_directory, "data", "airbnb", "barcelona", "neighbourhoods.geojson"))
```

```{r}
plot(barcelona_map)
```

```{r}
bar_listings <- read.csv(file.path(project_directory, "data" ,"airbnb", "barcelona", "listings_cleaned.csv"))
```

```{r}
bar_listings_with_geom <- merge(bar_listings, barcelona_map, by.x = "neighbourhood", by.y = "neighbourhood", all.x = TRUE)
bar_listings_sf <- st_as_sf(bar_listings_with_geom)
st_crs(bar_listings_sf) <- st_crs(barcelona_map)
```

```{r}
# this geometry seems to have an error
bar_listings_sf <- bar_listings_sf[bar_listings_sf$neighbourhood_group.y != 'Sant Martí', ]
```

```{r}
bar_listings_sf_sample <- sample_frac(bar_listings_sf, size = 1000/nrow(ams_listings_sf), replace = FALSE)
```

```{r}
barcelona_nbq <- poly2nb(bar_listings_sf_sample, queen=TRUE)
barcelona_listw <- nb2listw(barcelona_nbq)
```

## Euskadi

```{r}
euskadi_map <- st_read(file.path(project_directory, "data", "airbnb", "euskadi", "neighbourhoods.geojson"))
```

```{r}
plot(euskadi_map)
```

```{r}
eus_listings <- read.csv(file.path(project_directory, "data" ,"airbnb", "euskadi", "listings_cleaned.csv"))
```

```{r}
eus_listings_with_geom <- merge(eus_listings, euskadi_map, by.x = "neighbourhood", by.y = "neighbourhood", all.x = TRUE)
eus_listings_sf <- st_as_sf(eus_listings_with_geom)
st_crs(eus_listings_sf) <- st_crs(euskadi_map)
```

```{r}
# this geometry seems to have an error
eus_listings_sf <- eus_listings_sf[eus_listings_sf$neighbourhood_group.y != 'Sant Martí', ]
```

```{r}
eus_listings_sf_sample <- sample_frac(eus_listings_sf, size = 1000/nrow(eus_listings_sf), replace = FALSE)
```

```{r}
euskadi_nbq <- poly2nb(eus_listings_sf_sample, queen=TRUE)
euskadi_listw <- nb2listw(euskadi_nbq)
```

## Girona

```{r}
girona_map <- st_read(file.path(project_directory, "data", "airbnb", "girona", "neighbourhoods.geojson"))
```

```{r}
plot(girona_map)
```

```{r}
gir_listings <- read.csv(file.path(project_directory, "data" ,"airbnb", "girona", "listings_cleaned.csv"))
```

```{r}
gir_listings_with_geom <- merge(gir_listings, girona_map, by.x = "neighbourhood", by.y = "neighbourhood", all.x = TRUE)
gir_listings_sf <- st_as_sf(gir_listings_with_geom)
st_crs(gir_listings_sf) <- st_crs(girona_map)
```

```{r}
# this geometry seems to have an error
gir_listings_sf <- gir_listings_sf[gir_listings_sf$neighbourhood != 'Sant Martí', ]
```

```{r}
gir_listings_sf_sample <- sample_frac(gir_listings_sf, size = 1000/nrow(gir_listings_sf), replace = FALSE)
```

```{r}
# Compute centroids of polygons
centroids <- st_centroid(gir_listings_sf_sample)

# Compute k nearest neighbors for centroids
k <- 5  # Number of nearest neighbors
girona_knn <- knn2nb(knearneigh(centroids, k = k))

# Construct neighbor list weights
girona_listw <- nb2listw(girona_knn, style = "W")
```

```{r}
# girona_nbq <- poly2nb(gir_listings_sf_sample, queen=TRUE)
# girona_listw <- nb2listw(girona_nbq, style = "W")
```

## Trying to combine Barcelona and Girona

```{r}
library(dplyr)

# Take 500 observations from gir_listings_sf_sample
gir_sample <- gir_listings_sf_sample %>%
  sample_n(500, replace = FALSE)

# Take 500 observations from bar_listings_sf_sample
bar_sample <- bar_listings_sf_sample %>%
  sample_n(500, replace = FALSE)

# Combine the samples
combined_sample <- bind_rows(gir_sample, bar_sample)
```

```{r}
# Compute centroids of polygons
centroids2 <- st_centroid(combined_sample)

girbar_knn <- knn2nb(knearneigh(centroids2, k = k))

girona_bar_listw <- nb2listw(girbar_knn, style = "W")
```

# Geographically Weighted Regression

```{r}
eq <- price ~ latitude + longitude + room_type + minimum_nights + number_of_reviews
```

## Barcelona Error Model

```{r}
error_model_b = errorsarlm(eq, data=bar_listings_sf_sample, listw= barcelona_listw, zero.policy=TRUE)
summary(error_model_b, Nagelkerke=T)
```

## Girona Error Model

```{r}
error_model_g = errorsarlm(eq, data=gir_listings_sf_sample, listw= girona_listw, zero.policy=TRUE)
summary(error_model_g, Nagelkerke=T)
```

## Girona and Barcelona Error Model

```{r}
error_model_g_b = errorsarlm(eq, data=combined_sample, listw= girona_bar_listw, zero.policy=TRUE)
summary(error_model_g_b, Nagelkerke=T)
```

need to find a way to combine multiple results because it takes ages to run (so run it in batches but get one final summary)
