---
title: "Data Enrichement"
output: html_document
date: "2024-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
easypackages::packages ("sf", "sp", "spdep", "spatialreg", "GWmodel", "tmap", "mapview", "car", "RColorBrewer", 
                        "cowplot", "leafsync", "leaflet.extras2", "mapview", "tidyverse", "patchwork")
```

```{r}
project_directory <- dirname(getwd())
```

# Loading Data

## Toronto Map

```{r}
toronto_geojson_file <- file.path(project_directory, "data", "geodata", "neighbourhoods.geojson")
toronto <- st_read(toronto_geojson_file)
```

```{r}
# the AREA_NAME is the name of the neighbourhood
# we need to clean the text so it is the same as all the other files
toronto$AREA_NAME <- tolower(trimws(gsub("\\(\\d+\\)", "", toronto$AREA_NAME)))
toronto$AREA_NAME <- gsub("\\(\\d+\\)", "", toronto$AREA_NAME)
toronto$AREA_NAME <- gsub("[[:punct:]]", "", toronto$AREA_NAME)

names(toronto)[names(toronto) == "AREA_NAME"] <- "neighbourhood"


toronto$neighbourhood[which(toronto$neighbourhood == 'cabbagetownsouth stjames town')] <- 'cabbagetownsouth st james town'
toronto$neighbourhood[which(toronto$neighbourhood == 'north stjames town')] <- 'north st james town'

toronto <- toronto[order(toronto$neighbourhood), ]
```

------------------------------------------------------------------------

```{r}
toronto$neighbourhood
```

```{r}
toronto_map <- ggplot() +
  geom_sf(data = toronto, fill = "lightblue") +
  theme_void()

toronto_map
```

## Census 2016

The census files contain 63 variables that will be used as indicators.

```{r}
#census2011_path <- file.path(project_directory, "data", "census2011.csv")
#census2011 <- read.csv(census2011_path, row.names = 1)

census2016_path <- file.path(project_directory, "data", "census2016.csv")
census2016 <- read.csv(census2016_path, row.names = 1)
census2016 <- census2016[order(census2016$neighbourhood), ]

#census2021_path <- file.path(project_directory, "data", "census2021.csv")
#census2021 <- read.csv(census2021_path, row.names = 1)
```

```{r}
names(census2016)
```

## Add Population Density

```{r}
toronto$area <- st_area(toronto)
```

```{r}
#census2011$population_density <- census2011$total_population/toronto$area
census2016$population_density <- census2016$total_population/toronto$area
#census2021$population_density <- census2021$total_population/toronto$area
```

## Add Toronto Geometries to Census 2016

```{r}
census2016_with_geom <- merge(census2016, toronto, by.x = "neighbourhood", by.y = "neighbourhood", all.x = TRUE)
census2016_sf <- st_as_sf(census2016_with_geom)
st_crs(census2016_sf) <- st_crs(toronto)
```

## Add Parks

```{r}
parks_geojson_file <- file.path(project_directory, "data", "geodata", "parks.geojson")
parks <- st_read(parks_geojson_file)
names(parks)[names(parks) == "AREA_NAME"] <- "neighbourhood"
parks <- parks[order(parks$neighbourhood), ]
```

```{r}
parks$neighbourhood <- tolower(parks$neighbourhood)
parks$neighbourhood <- gsub("[[:punct:]0-9]", "", parks$neighbourhood)
```

```{r}
parks <- parks %>%
  group_by(neighbourhood)

# Calculate the area of each park
parks <- parks %>%
  mutate(park_area = st_area(geometry))

# Sum the area per neighbourhood
parks <- parks %>%
  group_by(neighbourhood) %>%
  summarise(total_park_area = sum(park_area))

# Add the neighbourhood area
parks <- parks %>%
  mutate(neighbourhood_area = toronto$area)

# Calculate how much of the neighbourhood is a park
parks <- parks %>%
  mutate(proportion = total_park_area/neighbourhood_area)
```

```{r}
census2016_sf <- census2016_sf %>%
  mutate(proportion_park_area = parks$proportion)

census2016_sf$proportion_park_area <- as.numeric(census2016_sf$proportion_park_area)
```

## Add Libraries

```{r}
libraries_geojson_file <- file.path(project_directory, "data", "geodata", "libraries.geojson")
libraries<- st_read(libraries_geojson_file)
names(libraries)[names(libraries) == "AREA_NAME"] <- "neighbourhood"
libraries <- libraries[order(libraries$neighbourhood), ]
```

```{r}
# data cleaning
libraries$neighbourhood <- tolower(libraries$neighbourhood)
libraries$neighbourhood <- gsub("[[:punct:]0-9]", "", libraries$neighbourhood)
libraries$neighbourhood <- trimws(libraries$neighbourhood)

libraries$neighbourhood[which(libraries$neighbourhood == 'cabbagetownsouth stjames town')] <- 'cabbagetownsouth st james town'
libraries$neighbourhood[which(libraries$neighbourhood == 'north stjames town')] <- 'north st james town'
```

```{r}
# group by neighbourhood to sum up number of libraries in each
libraries <- libraries %>%
  group_by(neighbourhood) %>%
  summarise(num_libraries = n())
```

```{r}
# some neighbourhoods have no libraries, but we still need them in the data
missing_neighborhoods <- setdiff(toronto$neighbourhood, libraries$neighbourhood)
length(missing_neighborhoods)

toronto_missing <- toronto[toronto$neighbourhood %in% missing_neighborhoods, ]
toronto_missing <- subset(toronto, neighbourhood %in% missing_neighborhoods, select = c("neighbourhood", "geometry"))
toronto_missing$num_libraries <- 0
```

```{r}
# add the missing neighbourhoods
libraries <- rbind(libraries, toronto_missing)
```

```{r}
census2016_sf <- census2016_sf %>%
  mutate(num_libraries = libraries$num_libraries)
```

## Add Police Facilities

```{r}
police_geojson_file <- file.path(project_directory, "data", "geodata", "distance_to_police.geojson")
police <- st_read(police_geojson_file)
names(police)[names(police) == "AREA_NAME"] <- "neighbourhood"
police <- police[order(police$neighbourhood), ]
```

```{r}
police$neighbourhood <- tolower(police$neighbourhood)
police$neighbourhood <- gsub("[[:punct:]0-9]", "", police$neighbourhood)
police$neighbourhood <- trimws(police$neighbourhood)
```

```{r}
census2016_sf <- census2016_sf %>%
  mutate(closest_police_facility = police$HubDist)
```

This shows the closest police facility for every neighbourhood (measured in km).

```{r}
# Overlay libraries
police_plot <- toronto_map +
  geom_sf(data = police, color = "yellow", size = 1) +
  theme_void()

# Print the map
print(police_plot)
```
